import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/thumbnail">Thumbnail</Link>
        </li>
        <li>
          <Link to="/aboutthisfile">Aboutthisfile</Link>
        </li>
        <li>
          <Link to="/whatsinthis">Whatsinthis</Link>
        </li>
        <li>
          <Link to="/practicedesigns">Practicedesigns</Link>
        </li>
        <li>
          <Link to="/homepage">Homepage</Link>
        </li>
        <li>
          <Link to="/shoppingcart">Shoppingcart</Link>
        </li>
        <li>
          <Link to="/productpage">Productpage</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
